name: cliptown_app
description: "Encrypted cross-platform clipboard history and device sync."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cliptown_interfaces:
    git:
      url: https://github.com/cliptown/cliptown-interfaces.git
      ref: 5d41bd7406e6f588377585612855f120701ac7ac
      path: generated/dart
  supabase_flutter: ^2.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
