#!/usr/bin/env python3
"""Remove dev-only plugins from Flutter's generated Android registrant."""

from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PLUGIN_METADATA = ROOT / ".flutter-plugins-dependencies"
REGISTRANT = (
    ROOT
    / "android"
    / "app"
    / "src"
    / "main"
    / "java"
    / "io"
    / "flutter"
    / "plugins"
    / "GeneratedPluginRegistrant.java"
)
GENERATED_HEADER = "This file is generated by the Flutter tool"


def android_dev_plugins() -> tuple[str, ...]:
    metadata = json.loads(PLUGIN_METADATA.read_text(encoding="utf-8"))
    plugins = metadata.get("plugins", {}).get("android", [])
    return tuple(
        plugin["name"]
        for plugin in plugins
        if plugin.get("dev_dependency") is True
    )


def remove_registration(text: str, plugin_name: str) -> str:
    block = re.compile(
        r"\n    try \{\n"
        r"(?:(?!\n    \} catch \(Exception e\) \{).)*"
        r"\n    \} catch \(Exception e\) \{\n"
        r'      Log\.e\(TAG, "Error registering plugin '
        + re.escape(plugin_name)
        + r', [^"]+", e\);\n'
        r"    \}",
        re.DOTALL,
    )
    updated, count = block.subn("", text)
    if count != 1:
        raise SystemExit(
            f"expected exactly one generated registration for {plugin_name}; found {count}"
        )
    return updated


def main() -> None:
    if not REGISTRANT.is_file():
        print("Flutter generated no source-tree Android plugin registrant; nothing to filter.")
        return

    original = REGISTRANT.read_text(encoding="utf-8")
    if GENERATED_HEADER not in original:
        raise SystemExit(f"refusing to modify non-generated file: {REGISTRANT}")

    dev_plugins = android_dev_plugins()
    if not dev_plugins:
        print("Flutter declared no Android dev-dependency plugins; registrant unchanged.")
        return

    updated = original
    for plugin_name in dev_plugins:
        updated = remove_registration(updated, plugin_name)

    for plugin_name in dev_plugins:
        if f"Error registering plugin {plugin_name}," in updated:
            raise SystemExit(f"dev-only plugin registration remains: {plugin_name}")

    REGISTRANT.write_text(updated, encoding="utf-8")
    print("Removed Android dev-only plugin registrations: " + ", ".join(dev_plugins))


if __name__ == "__main__":
    main()
